@Restaurats.API_HostAddress = https://localhost:7163


POST {{Restaurats.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "name": "Tasty Bites test",
  "description": "A cozy place with delicious homemade meals.",
  "category": "Casual Dining",
  "city": "Los Angeles",
  "street": "456 Sunset Boulevard",
  "postalCode": "90028",
  "logoSasUrl": "https://example.com/tasty-bites-logo.png",
  "dishes": [
    {
      "name": "Spaghetti Carbonara",
      "description": "Classic Italian pasta with creamy sauce and pancetta.",
      "price": 14.99,
      "kiloCalories": 750
    }]
}

###
GET {{Restaurats.API_HostAddress}}/api/restaurants

###

GET {{Restaurats.API_HostAddress}}/api/restaurants

###
